const UPDATE_LOCATIONS = 'player/UPDATE_LOCATIONS';
const UPDATE_SOCIAL = 'player/UPDATE_SOCIAL';
const UPDATE_GOALS = 'player/UPDATE_GOALS';
const UPDATE_STATE_LOCATION = 'player/UPDATE_STATE_LOCATION';

export default { UPDATE_LOCATIONS, UPDATE_SOCIAL, UPDATE_GOALS, UPDATE_STATE_LOCATION };
